# Generated by Django 3.1.1 on 2020-09-18 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200918_1209'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='grupa',
            field=models.TextField(default='-', max_length=50),
        ),
    ]
