# Generated by Django 3.1.1 on 2020-09-16 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Uroki',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_field', models.DateField()),
                ('nomer_uroka', models.PositiveSmallIntegerField()),
                ('nomer_klassa', models.PositiveSmallIntegerField()),
                ('nazvanie_predmeta', models.TextField(max_length=25)),
                ('prepodavatel', models.TextField(max_length=60)),
                ('tema_uroka', models.TextField(max_length=250)),
                ('ssylka_na_urok', models.TextField(max_length=10000)),
                ('vremya_nachala_uroka', models.TextField()),
            ],
        ),
    ]
