# Generated by Django 3.1.1 on 2020-09-16 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shkola', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NomeraUroka',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomer_uroka', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='uroki',
            name='kommentaryi',
            field=models.TextField(default='-', max_length=10000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='uroki',
            name='nomer_uroka',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shkola.nomerauroka'),
        ),
    ]
