# Generated by Django 3.1.1 on 2020-09-16 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shkola', '0003_auto_20200916_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uroki',
            name='ssylka_na_urok',
            field=models.TextField(default='-', max_length=10000),
        ),
        migrations.AlterField(
            model_name='uroki',
            name='vremya_nachala_uroka',
            field=models.TextField(max_length=5),
        ),
    ]
