# Generated by Django 3.1.1 on 2020-09-17 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shkola', '0004_auto_20200916_1633'),
    ]

    operations = [
        migrations.CreateModel(
            name='Upravlenie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imya', models.TextField(default='-', max_length=50)),
                ('otchestvo', models.TextField(default='-', max_length=50)),
                ('familiya', models.TextField(default='-', max_length=50)),
                ('login', models.TextField(default='-', max_length=50)),
                ('parol', models.TextField(default='-', max_length=50)),
                ('email', models.TextField(default='-', max_length=50)),
                ('telefon', models.TextField(default='-', max_length=50)),
            ],
            options={
                'verbose_name': 'Преподаватель',
                'verbose_name_plural': 'Преподаватели',
            },
        ),
        migrations.AlterModelOptions(
            name='nomeraklassa',
            options={'verbose_name': 'Номер Класса', 'verbose_name_plural': 'Номера Классов'},
        ),
        migrations.AlterModelOptions(
            name='nomerauroka',
            options={'verbose_name': 'Номер Урока', 'verbose_name_plural': 'Номера Уроков'},
        ),
        migrations.AlterModelOptions(
            name='predmety',
            options={'verbose_name': 'Предмет', 'verbose_name_plural': 'Предметы'},
        ),
        migrations.AlterModelOptions(
            name='prepodavately',
            options={'verbose_name': 'Преподаватель', 'verbose_name_plural': 'Преподаватели'},
        ),
        migrations.AlterModelOptions(
            name='uroki',
            options={'verbose_name': 'Урок', 'verbose_name_plural': 'Уроки'},
        ),
        migrations.AddField(
            model_name='prepodavately',
            name='email',
            field=models.TextField(default='-', max_length=50),
        ),
        migrations.AddField(
            model_name='prepodavately',
            name='login',
            field=models.TextField(default='-', max_length=50),
        ),
        migrations.AddField(
            model_name='prepodavately',
            name='parol',
            field=models.TextField(default='-', max_length=50),
        ),
        migrations.AddField(
            model_name='prepodavately',
            name='telefon',
            field=models.TextField(default='-', max_length=50),
        ),
        migrations.AlterField(
            model_name='prepodavately',
            name='familiya',
            field=models.TextField(default='-', max_length=50),
        ),
        migrations.AlterField(
            model_name='prepodavately',
            name='imya',
            field=models.TextField(default='-', max_length=50),
        ),
        migrations.AlterField(
            model_name='prepodavately',
            name='otchestvo',
            field=models.TextField(default='-', max_length=50),
        ),
        migrations.AlterField(
            model_name='uroki',
            name='date_field',
            field=models.DateField(verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='uroki',
            name='kommentaryi',
            field=models.TextField(max_length=10000, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='uroki',
            name='nazvanie_predmeta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shkola.predmety', verbose_name='Название предмета'),
        ),
        migrations.AlterField(
            model_name='uroki',
            name='nomer_klassa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shkola.nomeraklassa', verbose_name='Номер класса'),
        ),
        migrations.AlterField(
            model_name='uroki',
            name='nomer_uroka',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shkola.nomerauroka', verbose_name='Номер урока'),
        ),
        migrations.AlterField(
            model_name='uroki',
            name='prepodavatel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shkola.prepodavately', verbose_name='Преподаватель'),
        ),
        migrations.AlterField(
            model_name='uroki',
            name='ssylka_na_urok',
            field=models.TextField(default='-', max_length=10000, verbose_name='Ссылка на урок'),
        ),
        migrations.AlterField(
            model_name='uroki',
            name='tema_uroka',
            field=models.TextField(max_length=250, verbose_name='Тема Урок'),
        ),
        migrations.AlterField(
            model_name='uroki',
            name='vremya_nachala_uroka',
            field=models.TextField(max_length=5, verbose_name='Время начала урока'),
        ),
    ]
