# Generated by Django 3.1.1 on 2020-09-18 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shkola', '0006_auto_20200918_0743'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExtUser',
        ),
    ]
